name: Publish to GitHub Pages

on:
  push:
    branches:
      - main # Cambia 'main' por tu rama principal si es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      run: |
        mkdir -p ./gh-pages
        cp index.html ./gh-pages/index.html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
