name: Publish to GitHub Pages

on:
  push:
    branches:
      - gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build and Deploy
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          npm install # O si utilizas otro sistema de construcción, ajusta esta línea
          npm run build # O comando que uses para construir tu sitio web
          git add .
          git commit -m "Deploying to GitHub Pages"
          git push
